task default: %w[similarity]

task :similarity do
    require 'similarity'
    require 'csv'
    CSV.foreach('words.csv', :headers => false) do |row|
      puts Similarity.distance_between(row[0], row[1])
    end
end